### ISSUE TITLE
Google Cloud Speech API 에러에 대한 이슈 및 의견 요청

### ISSUE THREAD

**Issue by hJayLee** [pyj9293/iothome#4]
> connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
File "transcribe_streaming.py", line 240, in <module>
main()
File "transcribe_streaming.py", line 219, in main
with record_audio(RATE, CHUNK) as buffered_audio_data:
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "transcribe_streaming.py", line 120, in record_audio
stream_callback=functools.partial(_fill_buffer, buff),
File "/home/pi/python-docs-samples/speech/grpc/env/local/lib/python2.7/site-packages/pyaudio.py", line 750, in open
stream = Stream(self, *args, **kwargs)
File "/home/pi/python-docs-samples/speech/grpc/env/local/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

위와 같은 에러 발생으로 이전부터 마이크 및 사운드 카드 설정에 관련된 문제로 판단하였습니다.
결과적으로 마이크를 마이크로서 인식될 것이라는 생각이 잘못된 것이었고, 마이크는 하나의 사운드카드로 인식되어 기존에 라즈베리파이에 내장된 사운드카드가 아닌 마이크를 디폴트로 설정하여 해결하였습니다.
현재 마이크 인식 및 녹음기능까지 완벽하게 동작합니다.

**Comment by hJayLee** [comment]
> connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
File "transcribe_streaming.py", line 240, in <module>
main()
File "transcribe_streaming.py", line 219, in main
with record_audio(RATE, CHUNK) as buffered_audio_data:
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "transcribe_streaming.py", line 120, in record_audio
stream_callback=functools.partial(_fill_buffer, buff),
File "/home/pi/python-docs-samples/speech/grpc/env/local/lib/python2.7/site-packages/pyaudio.py", line 750, in open
stream = Stream(self, *args, **kwargs)
File "/home/pi/python-docs-samples/speech/grpc/env/local/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

위와 같은 에러 발생으로 이전부터 마이크 및 사운드 카드 설정에 관련된 문제로 판단하였습니다.
결과적으로 마이크를 마이크로서 인식될 것이라는 생각이 잘못된 것이었고, 마이크는 하나의 사운드카드로 인식되어 기존에 라즈베리파이에 내장된 사운드카드가 아닌 마이크를 디폴트로 설정하여 해결하였습니다.
현재 마이크 인식 및 녹음기능까지 완벽하게 동작합니다.

**Comment by hJayLee** [comment]
> connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
File "transcribe_streaming.py", line 240, in <module>
main()
File "transcribe_streaming.py", line 231, in main
listen_print_loop(recognize_stream)
File "transcribe_streaming.py", line 181, in listen_print_loop
raise RuntimeError('Server error: ' + resp.error.message)
RuntimeError: Server error: Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 184.99866700451821 second(s). Required at least: 185 second(s).

마이크 동작에 관해서는 해결하였는데, 마이크를 통한 음성인식 기능을 실행하면 위와 같이 이전과 다른 에러가 발생합니다.

**Comment by hJayLee** [comment]
![2017-01-06 3 37 53](https://cloud.githubusercontent.com/assets/22610690/21709669/3b1801be-d426-11e6-83d4-4b2b474773c1.png)

우분투Mate 설치 후 이전과 같은 방법으로 음성인식 API를 적용한 결과 마이크 문제(사운드 카드 문제) 및 API에 대한 문제 전부 해결되었습니다. 애초에 라즈비안을 사용하면서 API와의 설정이나 호환성이 문제였던 것으로 보입니다. **문제해결에 대한 부분은 아니지만 아래 주소는 음성인식 API 설치와 설정에 대해 참고한 블로그 링크입니다.**

> http://blog.naver.com/chandong83/220826470486
